services:
  image-converter:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: image-converter
    ports:
      - "3001"

    restart: unless-stopped
    env_file:
      - .env
